name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-sh:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Orbital Transfer
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          export ORBITAL_LAUNCH_SITE_DIR=$(cd .. && pwd)/_orbital/external/orbital-transfer/launch-site
          export ORBITAL_TEST_DIR=$GITHUB_WORKSPACE
          git clone --recursive \
                  https://github.com/orbital-transfer/launch-site.git \
                  $ORBITAL_LAUNCH_SITE_DIR
          export PATH="$ORBITAL_LAUNCH_SITE_DIR"/vendor/p5-Orbital-Launch/bin:$PATH
          echo "$ORBITAL_LAUNCH_SITE_DIR"/vendor/p5-Orbital-Launch/bin >> $GITHUB_PATH
          perl -S orbitalism bootstrap auto
      - name: Use Orbital Transfer
        shell: bash
        run: |
          perl -S orbitalism
          perl -S orbitalism test
